#include "halcon_pch_t.hpp"
#include"halconcpp/HalconCpp.h"

using namespace HalconCpp;

TEST(HalconExample, DetectCircles)
{
    try
    {
        // 初始化 Halcon 窗口
        HObject  ho_Regions, ho_Circles;
        HTuple hv_WindowID;


        // 创建窗口以显示图像
        SetWindowAttr("background_color", "black");
        OpenWindow(0, 0, 512, 512, 0, "visible", "", &hv_WindowID);
        HDevWindowStack::Push(hv_WindowID);

        // Local iconic variables
        HObject  ho_Image, ho_GrayImage, ho_Rectangle;
        HObject  ho_ImageReduced, ho_ModelContours, ho_Image1, ho_ContoursAffineTrans;

        // Local control variables
        HTuple  hv_WindowHandle, hv_Row1, hv_Column1;
        HTuple  hv_Row2, hv_Column2, hv_ModelID, hv_Row, hv_Column;
        HTuple  hv_Angle, hv_Score, hv_HomMat2D;

        //Image Acquisition 01: Code generated by Image Acquisition 01
        ReadImage(&ho_Image, "C:/Users/rw/Desktop/temp/4be85a13-4196-4ae1-bb3c-ccea8d1d27fa.png");
        if (HDevWindowStack::IsOpen())
            hv_WindowHandle = HDevWindowStack::GetActive();
        //彩色转灰度
        Rgb1ToGray(ho_Image, &ho_GrayImage);
        //画一个矩形
        DrawRectangle1(hv_WindowHandle, &hv_Row1, &hv_Column1, &hv_Row2, &hv_Column2);
        //画矩形
        GenRectangle1(&ho_Rectangle, hv_Row1, hv_Column1, hv_Row2, hv_Column2);

        //图像类型变量qimage    数值类型变量

        ReduceDomain(ho_GrayImage, ho_Rectangle, &ho_ImageReduced);

        //创建模板
        CreateShapeModel(ho_ImageReduced, "auto", -0.39, 0.79, "auto", "auto", "use_polarity",
            "auto", "auto", &hv_ModelID);
        //获取模板轮廓
        GetShapeModelContours(&ho_ModelContours, hv_ModelID, 1);

        ReadImage(&ho_Image1, "C:/Users/rw/Desktop/temp/f2e008f9-1ccd-42ea-94b0-cb25f39b9a47.png");

        FindShapeModel(ho_Image1, hv_ModelID, -0.39, 0.79, 0.5, 1, 0.5, "least_squares",
            0, 0.9, &hv_Row, &hv_Column, &hv_Angle, &hv_Score);


        //位置转换函数
        VectorAngleToRigid(0, 0, 0, hv_Row, hv_Column, hv_Angle, &hv_HomMat2D);

        //移动
        AffineTransContourXld(ho_ModelContours, &ho_ContoursAffineTrans, hv_HomMat2D);


        SUCCEED();
    }
    catch (HException& e)
    {
        std::cerr << "Halcon Error: " << e.ErrorMessage() << std::endl;
        FAIL();
    }
}